export const techs = [
  { name: 'Node JS' },
  { name: 'Angular' },
  { name: 'HTML' },
  { name: 'Javascript' },
  { name: 'CSS' },
  { name: 'ReactJS' },
  { name: 'Python' },
  { name: 'Java' },
  { name: 'Node JS' },
  { name: 'Typescript' },
  { name: 'GraphQL' },
  { name: 'Golang' },
  { name: 'Ruby' },
  { name: 'Spring' },
  { name: 'C++' },
  { name: 'C#' },
  { name: 'iOS' },
  { name: 'Android' },
  { name: 'Visual Basic' },
  { name: 'Django' },
  { name: 'SQL Server' },
  { name: 'MySQL' },
  { name: 'PostgresQL' },
  { name: 'Oracle' },
  { name: 'Xamarín' },
  { name: 'Nginx' },
  { name: 'Yarn' },
  { name: 'NPM' },
  { name: 'Docker' },
  { name: 'MongoDB' },
  { name: 'AWS' },
  { name: 'Kotlin' },
  { name: 'Swift' },
  { name: 'Heroku' },
  { name: 'GitHub' },
  { name: 'PHP' },
  { name: 'Firebase' },
  { name: 'Unity' },
  { name: 'Vue' },
  { name: 'GitLab' },
  { name: 'Redis' },
];
